sentinelhub/geopedia.py
tests/test_geopedia.py

Added method to extend query sent to geopedia, allowing filtering directly on geopedia.

Using geopedia filterExpression for querying

---

sentinelhub/config.json
sentinelhub/config.py
sentinelhub/download/sentinelhub_client.py
sentinelhub/sentinelhub_rate_limit.py
tests/test_sentinelhub_rate_limit.py

Co-authored-by: AleksMat <matej.aleksandrov@sinergise.com>

Implementation of the simple rate limit

---

sentinelhub/constants.py
tests/test_constants.py

Improvements of `CRS` object that will better support working with the new versions of `pyproj` and `geopandas`.

improved CRS parsing, added CRS.pyproj_crs method and unit tests

---

sentinelhub/constants.py

- Support for non-eocloud Sentinel5P configuration (https://creodias.sentinel-hub.com)
- MINQA parameter support for Sentinel5P data
I tested the features by hand.

Better Sentinel5P support

---

README.md
docs/source/install.rst

Changes:
- added conda installation instructions
- added conda badge to readme

added Conda badge and install instruction

---

README.md
docs/source/configure.rst
sentinelhub/geopedia.py
tests/test_geopedia.py

Changes:
- Fixed issue where `GeopediaFeatureIterator.get_size` changed the state of loaded features but didn't store features.
- Added some tests for this case
- Updated some SH links in documentation

Fixed issue with GeopediaFeatureIterator

---

sentinelhub/data_collections.py
sentinelhub/sentinelhub_catalog.py
sentinelhub/sentinelhub_request.py

This PR implements dem_instance parameter for DEM collections.

demInstance parameter for DEM collections.

---

sentinelhub/areas.py
tests/test_areas.py

- 1st commit adds `offset` parameter to UTM splitters,
- 2nd commit makes various minor improvements and fixes in the module

Utm splitter offset

---

sentinelhub/constants.py
tests/test_constants.py

Changes:
- removed deprecated `skip_equivalent` parameter,
- handled case where `pyproj.CRS.to_epsg` was returning `None`,
- minor style updates

Crs updates

---

sentinelhub/aws.py
sentinelhub/aws_safe.py

This PR address issue #116
This bug fix insert some checks to build the SAFE structure of reprocessed Sentinel-2 L2A products appropriately.

Fix for issue #116

---

sentinelhub/constants.py
sentinelhub/geo_utils.py
sentinelhub/geometry.py
tests/test_geo_utils.py

Changes:
- Added `always_xy` parameter and set its default value to `True`, which is different than what `pyproj` uses for default.
- Refactored existing and added new unit tests that verify correctness of transformations.
- Minor code style improvements.

pyproj transformation improvement - added support for always_xy

---

pylintrc
requirements-dev.txt
sentinelhub/__init__.py
sentinelhub/testing_utils.py
tests/conftest.py
tests/test_all.py
tests/test_areas.py
tests/test_aws.py
tests/test_aws_safe.py
tests/test_commands.py
tests/test_constants.py
tests/test_data_collections.py
tests/test_data_request.py
tests/test_decode.py
tests/test_download.py
tests/test_fis.py
tests/test_geometry.py
tests/test_geopedia.py
tests/test_io_utils.py
tests/test_ogc.py
tests/test_opensearch.py
tests/test_sentinelhub_byoc.py
tests/test_sentinelhub_rate_limit.py
tests/test_sentinelhub_request.py
tests/test_session.py
tests/test_sh_utils.py
tests/test_time_utils.py

Most of the tests were still using `unittest` for testing, so I rewrote the tests to `pytest`.
I also removed some old tests for which it turns out that they were never checked and don't really make sense.

Change remaining tests to pytest

---

.travis.yml
setup.py

Adds official support for Python 3.9. Additionally it switches integration tests from 3.7 to 3.9.

Support for Python 3.9

---

examples/fis_request.ipynb
sentinelhub/data_collections.py
tests/test_data_collections.py
tests/test_fis.py
tests/test_ogc.py
tests/test_sentinelhub_byoc.py
tests/test_sentinelhub_catalog.py
tests/test_sentinelhub_request.py

The reason for renaming is to be in line with Sentinel Hub service. In the future these collections will be maintained by type of sensor instead of type of satellite.
@tomislijepcevic, the exact renaming is written [here](https://github.com/sentinel-hub/sentinelhub-py/blob/feat/rename-landsat-collections/sentinelhub/data_collections.py#L211). Could you check if you agree with the new names?

Rename Landsat DataCollection enums

---

.gitignore
README.md
docs/Makefile
docs/source/conf.py
docs/source/index.rst
docs/source/install.rst
requirements-docs.txt

Updates the content of Readme and configures automatic parsing of Readme into documentation.

Readme update

---

docs/source/index.rst
docs/source/logging.rst
examples/utils.py
sentinelhub/config.py
sentinelhub/download/client.py
sentinelhub/download/handlers.py
sentinelhub/download/sentinelhub_client.py
sentinelhub/download/sentinelhub_statistical_client.py
sentinelhub/exceptions.py
sentinelhub/sentinelhub_rate_limit.py
sentinelhub/sentinelhub_session.py

Adds more logging to download clients and a new section to the docs, describing how to enable and improve logging.
While making the changes I also did some minor cleanups of code I encountered along the way.

Add more logging

---

sentinelhub/constants.py
sentinelhub/sentinelhub_request.py
tests/test_constants.py

Makes the two operations pseudo-inverses of each other.

Make Mimetype `from_string` parse `get_string` output

---

examples/batch_processing.ipynb
examples/byoc_request.ipynb
examples/data_search.ipynb
pylintrc
sentinelhub/__init__.py
sentinelhub/areas.py
sentinelhub/config.py
sentinelhub/sentinelhub_batch.py
sentinelhub/sentinelhub_byoc.py
sentinelhub/sentinelhub_catalog.py
sentinelhub/sentinelhub_session.py
sentinelhub/sh_utils.py
tests/test_sentinelhub_batch.py
tests/test_sentinelhub_catalog.py

It also adds `sh_auth_base_url` config parameter, updates documentation notebooks and tests.

Major change in SentinelHubBatch interface

---

sentinelhub/data_collections_bands.py

I fixed a couple of issues regarding metabands and their units. I also double-checked that everything else is ok.

Fixed metabands and their units

---

.github/workflows/ci_action.yml
README.md
docs/source/install.rst
sentinelhub/constants.py
setup.py

Everything related to 3.6 has been removed. Tests for Python 3.10 pass.

Removed support for Python 3.6 and added support for Python 3.10

---

sentinelhub/constants.py
tests/test_constants.py

Updates and improvements needed for https://github.com/sentinel-hub/eo-learn/pull/347#discussion_r778714451

MimeType enums needed for eo-learn and an extra method

---

sentinelhub/data_collections_bands.py
sentinelhub/fis.py

The PR fixes units for surface temperature bands in LandSat collections.
Additionally, it adds a deprecation warning in FisService (in favour of Statistical API.)

LandSat collection units

---

sentinelhub/constants.py
tests/test_constants.py

Fixes the interaction of CRS and numpy integers

---

README.md
sentinelhub/aws/request.py
sentinelhub/commands.py
sentinelhub/config.py
sentinelhub/constants.py
sentinelhub/data_request.py
sentinelhub/ogc.py
sentinelhub/sentinelhub_session.py
tests/test_commands.py
tests/test_fis.py

Changes:
- removed some deprecated content, handled some warnings,
- updated some docs, updated some links

Warnings and links updates

---

sentinelhub/download/client.py

Progress bar logic had to be moved within `with` loop because `executor` closing will wait for threads to finish.

Fixed an issue with progress bar in DownloadClient not working correctly

---

sentinelhub/areas.py
sentinelhub/base.py
sentinelhub/constants.py
sentinelhub/data_collections.py
sentinelhub/geo_utils.py
sentinelhub/time_utils.py

This time no significant code changes apart from annotations :D

Add more type annotations

---

.gitignore
requirements.txt
sentinelhub/api/base.py
sentinelhub/api/batch.py
sentinelhub/api/byoc.py
sentinelhub/api/utils.py
sentinelhub/areas.py
sentinelhub/base.py

In some of the cases the methods parse many inputs. It is far easier to work with if I replace them with a name while working:
```python
CollectionType = Union["ByocCollection", DataCollection, dict, str]
```
But i'm not sure what to do:
1. Inline the types.
2. Find some meaningful names for that (please help).
Other than this there are barely any code changes.

Add types to collection classes

---

sentinelhub/api/base.py
sentinelhub/api/batch.py
sentinelhub/api/byoc.py
sentinelhub/download/client.py
sentinelhub/download/handlers.py
sentinelhub/download/rate_limit.py
sentinelhub/download/request.py
sentinelhub/download/sentinelhub_client.py
sentinelhub/download/sentinelhub_statistical_client.py
sentinelhub/download/session.py
sentinelhub/io_utils.py
sentinelhub/time_utils.py
sentinelhub/type_utils.py

Sadly not all of the methods type easily, due to over-generalisation. I feel like this is not the time to refactor the code too much, so I mostly added some additional guards.

Add types to sentinelhub.download

---

.github/workflows/ci_action.yml
pyproject.toml
requirements-dev.txt
sentinelhub/api/base_request.py
sentinelhub/api/fis.py
sentinelhub/api/opensearch.py
sentinelhub/api/process.py
sentinelhub/api/statistical.py
sentinelhub/api/utils.py
sentinelhub/aws/client.py
sentinelhub/aws/commands.py
sentinelhub/aws/data.py
sentinelhub/aws/data_safe.py
sentinelhub/aws/request.py
sentinelhub/geopedia/core.py
sentinelhub/geopedia/request.py

This MR adds the remaining types to AWS and geopedia subpackages.
I then cleaned the docstrings to remove :type: mentions.
Finally I added mypy to CI.

Make `sentinelhub-py` mypy compliant

---

sentinelhub/aws/constants.py

These changes are required to enable the fetched products to support BioPhysical processing in SNAP.

Add outstanding MSK_CLASSI_B00 file from processing baseline 04.00

---

.github/workflows/ci_action.yml
examples/batch_processing.ipynb
examples/byoc_request.ipynb
examples/fis_request.ipynb
examples/utils.py
sentinelhub/aws/constants.py
setup.py
tests/download/test_rate_limit.py

Just a few very minor style improvements.

Minor improvements

---

sentinelhub/decoding.py
tests/download/test_handlers.py
tests/test_decode.py

Increasing test coverage and improving the way error messages are being parsed.

Tests for download handlers and improved error message parsing

---

examples/byoc_request.ipynb

fix byoc request example

---

sentinelhub/__init__.py
sentinelhub/api/base.py
sentinelhub/data_collections.py
tests/test_data_collections.py

These things were deprecated for quite a while now.

Removed some deprecations

---

sentinelhub/download/rate_limit.py
tests/download/test_rate_limit.py

New headers are configured and tests updated.

Updated rate limit headers

---

sentinelhub/__init__.py
sentinelhub/api/__init__.py
sentinelhub/api/batch/__init__.py
sentinelhub/api/batch/utils.py
tests/api/batch/test_utils.py

This approach follows the current sh-py ideology "we take care of everything".
Sadly this results in multiple heavy duty overloads.
The current MR is more of a showcase of how it can be done, but we should consider switching to two separate functions. There will be more copied code but less type-system magic

Adjust monitoring for batch statistical

---

sentinelhub/api/batch/statistical.py
sentinelhub/aws/__init__.py
sentinelhub/aws/batch.py
sentinelhub/aws/client.py
sentinelhub/aws/data.py
sentinelhub/aws/data_safe.py
sentinelhub/aws/request.py
sentinelhub/base.py

A class to download results from an S3 bucket and either return or save them locally. It is another implementation of `DataRequest` class. Besides that I also had to generalize and fix a few things in `AwsDownloadClient` to make this implementation possible.
The following will be done in next PRs:
- unit tests for `AwsBatchResults`,
- a method of `AwsBatchResults` that will be returning results in form of a pandas dataframe (maybe in the next package version?)

Utility for downloading Statistical Batch API results

---

requirements-dev.txt
sentinelhub/base.py
tests/aws/test_batch.py

Implemented tests for `AwsBatchResults`, added `show_progress` support to `DataRequest`, and updated some types.

Tests for AwsBatchResults

---

sentinelhub/api/fis.py
sentinelhub/api/ogc.py
sentinelhub/download/sentinelhub_client.py
sentinelhub/download/session.py
tests/download/test_sentinelhub_client.py
tests/download/test_session.py

The headers are now automatically added to each request to SH services.

Fixed and genralized handling of user-agent headers

---

sentinelhub/api/batch/base.py
sentinelhub/api/batch/process.py

Closes https://github.com/sentinel-hub/sentinelhub-py/issues/320

specialize conditionals in batch client

---

sentinelhub/api/ogc.py

In one of the refactorings we missed the classic mutability+no-copy issue.

Fix OGC bug with parameters being re-encoded

---

sentinelhub/__init__.py
sentinelhub/os_utils.py

Lets give the users a few months to fix their code.

Make os_utils deprecation soft

---

tests/test_areas.py

I added some tests for the BBoxSplitter initialized with split_size parameter.

Add tests for bbox_splitter

---

sentinelhub/areas.py

Added some minor fix in the docstrings

Add units detail in BBoxSplitter docstrings

---

examples/batch_statistical.ipynb

I fixed some wording mistake and client initialization

160 improve batch statistical example

---

.flake8
sentinelhub/commands.py
sentinelhub/config.py
sentinelhub/data_collections.py
sentinelhub/download/session.py

Some quotes were changed, error ignored until 3.8 comes around

change some quotes, ignore B028

---

sentinelhub/constants.py
sentinelhub/testing_utils.py

Also adjust types in testing_utils to not waste another MR for such a minor thing

Fix CRS class to support fiona 1.9.0

---

sentinelhub/constants.py
tests/test_constants.py

Nothing major, but it's good to keep things updated

small improvements to tests of `constants` module

---

sentinelhub/decoding.py
sentinelhub/io_utils.py
tests/test_io_utils.py

There was no reason to have all those miniature functions, since they weren't used anywhere. Some not even in the magic functions :joy:

Simplify io utils

---

docs/source/conf.py
examples/byoc_request.ipynb
requirements-docs.txt
sentinelhub/areas.py
sentinelhub/geometry.py

Changes:
- replaces `m2r2` with `sphinx_mbinclude`
- removes `m2r2` and `jinja2`
- update sphinx errors/issues in docs
- update sphinx error with nbconvert in notebook

Fix failing docs and update docs requirements

---

tests/test_time_utils.py

Reorder and split test cases, update testing constants.

Improve test time

---

sentinelhub/api/batch/base.py
sentinelhub/api/batch/statistical.py
tests/api/batch/test_statistical.py

deprecat cancel_job and add stop_job
add BatchRequestStatus and BatchUserAction
update test

Batch Statistical STOP status and action

---

sentinelhub/api/process.py
tests/api/test_process_async.py

Adds a function that (for a collection of IDs) checks which of the requests are still running.

Add async request query functionality

---

.github/workflows/ci_action.yml
.github/workflows/scheduled_caller.yml

More info in https://github.com/sentinel-hub/eo-learn/pull/662

Split github actions per trigger and make use of reusable workflows

---

docs/source/configure.rst

Fix research accounts docs

---

sentinelhub/api/process.py

still not sure where this one popped up (cant reproduce locally)

try fixing the newly found mypy issue

---

sentinelhub/areas.py

Add comment to ignore mypy mistake
