sentinelhub/aws.py
sentinelhub/commands.py

This is a relatively simple change that allows the user to specify which bands to download. For users who need only a subset of the available bands, this reduces requirements for download time, network bandwidth, and storage space.
I apologize for the pull request with no prior contact about this feature. I implemented it for my own use and afterward realized it might be useful to others.

Allow explicit band selection in both API and commandline tool

---

sentinelhub/aws.py

Should fix #8 
I'm assuming that a tile is defined by 1 or 2 digits followed by 3 letters.

Fix downloading tiles with single-digit UTM zone

---

.travis.yml

Environment variables needed in some tests are not exposed to build system during pull request builds, due to security reasons. These tests should be skipped in this situation.

Fix Travis build on pull requests

---

sentinelhub/download.py

This enables retrieval of credentials from the environment as described at:
https://boto3.readthedocs.io/en/latest/guide/configuration.html
For example, boto3 will retrieve credentials from environment variables or the EC2 instance metadata service, allowing us to avoid hardcoding credentials in a configuration file.

remove AWS credentials check and set in boto3 only if they are configured

---

sentinelhub/opensearch.py

tile_id is a str, so logging it with %d raises a TypeError.
Fixes #60

Fixed logging in get_tile_info

---

sentinelhub/geometry.py

Simple fix for misnaming coordinates
realated to: https://github.com/sentinel-hub/eo-learn/issues/79

x/y_min vs. min_x/y bug

---

sentinelhub/constants.py

Evalscripts (v2 and v3) in SentinelHub support output type, and when using OGC services it has to be aligned with the requested image format. This commit allows to get correct SH type based on requested image format.

image format to SH evalscript sample type

---

sentinelhub/data_request.py
sentinelhub/download.py

Number of threads started for a request is by default (None) number of processes multiplied by 5, see
https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor

threads by default is #processes multiplied by 5

---

Makefile
examples/aws_request.ipynb
examples/large_area_utilities.ipynb
sentinelhub/constants.py
sentinelhub/data_request.py

Used this by hand (not the `-w` option)
```
codespell --version
1.15.0
```

Minor typo fixes found with codespell

---

sentinelhub/sentinelhub_request.py
tests/test_sentinelhub_request.py

Properly update the dictionary objects when the `other_args` param is used.
The new function recursively loops over the `other_args` and only adds non-dict like values to assigned keys, meaning that you can provide a nested dictionary which will be used to update the internal dictionary object.

WIP: fix updating with other_args dict

---

sentinelhub/sentinelhub_request.py
tests/test_sentinelhub_request.py

In `SentinelHubRequest` it replaces `base_url` parameter by having `InputDataDict` objects. This simplifies the way a user has to build a request.

Handle request urls in SentinelHubRequest with InputDataDict

---

sentinelhub/constants.py
sentinelhub/data_collections.py
tests/test_config.py
tests/test_constants.py

When parsing `sentinelhub.CRS(pyproj.CRS(4326))` we now get a warning instead of an explicit error about the coordinate order. This way it is up to a user to correctly deal with coordinates.

CRS parsing shows a warning instead of an error

---

sentinelhub/aws.py
sentinelhub/aws_safe.py
sentinelhub/download/aws_client.py
sentinelhub/download/client.py
sentinelhub/download/sentinelhub_client.py
sentinelhub/geopedia.py
sentinelhub/ogc.py
sentinelhub/opensearch.py
sentinelhub/sentinelhub_batch.py

The following enables that `get_json` and `get_xml` helpers can be used by classes that inherit from `DownloadClient` without a need for another helper function.

Moved get_json and get_xml functions to DownloadClient methods

---

sentinelhub/config.py
tests/test_config.py

`download_timeout_seconds` and `download_sleep_time` can now be float or int type, instead of only int.

add floats to config allowed parameters

---

sentinelhub/sentinelhub_request.py
tests/test_sentinelhub_request.py

MimeType has an already implemented function to parse types, the function implement the logic to deal with parsing of  "jpeg"  and "jpg" file formats.

use parsing function when retriving type

---

sentinelhub/sentinelhub_request.py
tests/test_sentinelhub_request.py

bbox is not created if the user doesn't specify it.
I modified an already existing test in order to avoid doing too many requests. The modified test is `test_multipart_geometry`, since the results doesn't change from the previous version, where bbox was specified explicitly, I would say that there is no reason to create the bbox.

don't create bbox if not specified by user

---

sentinelhub/constants.py
sentinelhub/data_collections.py
sentinelhub/sentinelhub_catalog.py
sentinelhub/sentinelhub_request.py
sentinelhub/time_utils.py
tests/test_time_utils.py

This PR tweaks the time (interval) parsing in order to allow open-ended interval requests to (some) SH services. Additionally, it adds `has_cloud_coverage(=False)` flag to DataCollections and sets it to true to collections that have CC as queryable parameter.

Open time intervals and "cloudy" collections

---

docs/source/areas.rst
docs/source/conf.py
docs/source/docs.rst
docs/source/fis.rst
docs/source/sentinelhub_byoc.rst
sentinelhub/config.py
sentinelhub/download/client.py
sentinelhub/geometry.py
sentinelhub/sentinelhub_rate_limit.py
sentinelhub/sh_utils.py

I went through documentation pages and fixed various minor issues.
I did this mainly to try fixing a weird documentation issue where `automodule` functionality cannot be used in `areas.rst` file. If I try using it then the content of all module documentation pages suddenly disappears in the built documentation. I tried various things but still couldn't figure it out.

Minor documentation improvements

---

requirements-dev.txt
sentinelhub/aws.py
sentinelhub/data_collections.py
tests/test_data_collections.py

This solves the problem with the following procedure:
- define a custom `DataCollection` enum,
- pass the new enum to another process (by `pickle` serialization),
- deserialize the enum in the new process.
This enables that this object is used with Ray framework.

DataCollection transfer fix

---

sentinelhub/data_collections.py

I added new Landsat 7 and Landsat 1-5 collections. I intentionally didn't add any new integration tests but I made sure that Process API, Catalog and OGC requests work for each of them.
Note: tests are failing because of unrelated change on SH service.

Enums for new Landsat 7 and Landsat 1-5 collections

---

docs/source/areas.rst
docs/source/data_collections.rst
docs/source/data_request.rst
docs/source/download.aws_client.rst
docs/source/download.sentinelhub_client.rst
docs/source/download.sentinelhub_statistical_client.rst
docs/source/geometry.rst
docs/source/geopedia.rst
docs/source/ogc.rst
docs/source/sentinelhub_batch.rst
docs/source/sentinelhub_byoc.rst
docs/source/sentinelhub_catalog.rst
docs/source/sentinelhub_rate_limit.rst
docs/source/sentinelhub_request.rst
docs/source/sentinelhub_session.rst
docs/source/sentinelhub_statistical.rst
docs/source/sh_utils.rst

By adding `:inherited-members:` tag into docs classes will now also show methods that they inherited from their parent classes.

Updated Sphinx docs to show inherited members of classes

---

sentinelhub/config.py
tests/test_config.py

Instances of `SHConfig` are usually passed around in the code a lot, which means that some frameworks, such as eo-learn, would log it and write into a report. But the problem is that a representation of a config object reveals all its parameters, including its credentials.
This PR adds an option to hide credentials. It also refactors unit tests for `SHConfig` and adds a few new ones.

An option to hide config credentials

---

docs/source/configure.rst

Missing single quote inside of tutorial code block on line 62. 
Noticed this while running through the configuration directions and it triggered my OCD, lol.

missing single quote on sentinel-hub-configuration readthedocs page

---

sentinelhub/sentinelhub_catalog.py
tests/test_sentinelhub_catalog.py

In `SentinelHubCatalog.search` we also support searches by only a collection id, which in some cases of BYOC and batch collections might be more natural. This PR handles such a case correctly and adds a test.

Fixed catalog search by collection id

---

sentinelhub/config.py
sentinelhub/download/aws_client.py

Added a config parameter `aws_session_token` that allows configuring libraries with `SHConfig` instances with temporary IAM credentials that are usually used at EC2 machines (access id, key and STS token are all required to initialize `boto3`).

Support AWS session tokens

---

requirements.txt

This package does not depend on `wheel` being installed to run - there are no imports of `wheel` in the code. Indeed it's not even distributed as a wheel :)

Remove dependency on wheel

---

docs/source/conf.py

Removing GA analytics (from readthedocs, opting for GDPR compliant one).

Fathom analytics.

---

sentinelhub/aws.py
sentinelhub/aws_safe.py
sentinelhub/constants.py

Support the v04.00 processing baseline from ESA and allow the downloaded products to be used with FMask.

Modifications to support S2 v04.00

---

.github/ISSUE_TEMPLATE/help-support.md

Links were pointing to eo-learn docs instead of sentinelhub-py because these templates were at some point copied from eo-learn.

Fixed links in help issue template

---

sentinelhub/constants.py

The problem is that it takes about 100ms to initialize each `pyproj` object and the size of each one in memory is almost 1MB. Therefore, we neither want to initialize `pyproj` objects many times nor we want to keep many of them in memory. But usually we need to make a transformation between CRSs many times, hence we cache `pyproj` objects.
We used to think that low `maxsize` cache limits were completely sufficient for more or less all use cases. But I recently had a use case of running a batch job with 300K tiles from 20 different UTM zones. [Here in `BatchSplitter`](https://github.com/sentinel-hub/sentinelhub-py/blob/v3.5.0/sentinelhub/areas.py#L727), tiles are being transformed from WGS84 to its native UTM CRSs. It turns out the service is returning batch tiles in some arbitrary order …

Increased cache size for pyproj objects

---

sentinelhub/__init__.py
sentinelhub/api/__init__.py
sentinelhub/api/batch.py

In use cases, such as `BatchDownloadPipeline` in `eo-grow`, it is useful that monitoring of only analysis part can be used independently from monitoring the entire process.

Moved monitoring of batch analysis into a separate function

---

MANIFEST.in
setup.py

While the type annotations are severely lacking at this point, it still allows `mypy` to differentiate between different shpy classes in other packages.

Add py.typed file

---

.gitignore
pyproject.toml
sentinelhub/commands.py
sentinelhub/geometry.py
sentinelhub/os_utils.py
sentinelhub/testing_utils.py

Since `py.typed` is included we can now start adding type annotations. This won't be easy so we should probably start with the low-hanging fruit and work our way to (possibly code-breaking) large changes.
I believe we should do this change gradually and in many small MRs so that the changes are actually looked at.
I tried to change the code itself as little as possible. In some places the precise types are rather verbose (a tuple of 4 tuples and the likes...)

More type annotations

---

sentinelhub/constants.py
tests/test_constants.py

We define WGS 84 in pyproj with reversed coordinates and transforming such object to EPSG code works:
```Python
from pyproj import CRS
CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs").to_epsg()
>> 4326
```
But, as far as I understand, during saving to Geopackage and loading from Geopackage the following happens with the object:
```Python
from pyproj import CRS
wgs84 = CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
new_wgs84 = CRS(wgs84.to_wkt())
new_wgs84.to_epsg()
>> None
```
Because EPSG code somehow can't be reconstructed this becomes an issue in `sentinelhub.CRS` parsing. The fix relies on the following:
```Python
from pyproj import CRS
wgs84 = CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
new_wgs84 = CRS(wgs84.to_wkt())
wgs84 == new_wgs84
>> True
``` …

Improved parsing of WGS84 in CRS class

---

requirements-dev.txt
sentinelhub/config.py
tests/conftest.py
tests/test_config.py
tests/test_data_collections.py

The problem was that when an instance of `SHConfig` would be passed to a Ray worker it would lose `self._instance` because that is defined only as a class attribute. However, `self._instance` was being called in many methods, even in `__repr__`. So calling `repr(config)` on Ray worker would fail.
The PR only contains a fix and an extra test for this.More improvements will be done in near future where we will also aim to get autocomplete for config parameters.
This PR also removes and limits some overrides of `__getatt__` and `__getitem__` methods and also puts adds Ray to development requirements for Python version `<3.10`.

Fixed issue of passing SHConfig to Ray

---

sentinelhub/areas.py
sentinelhub/geometry.py

The MR comes in three commits, and I suggest it is best reviewed this way.
1. Change of `_make_split` so that it is now part of the super class, where all subclasses first set any attributes and then call `super().__init__`. This is a *90% there* improvement, because a 100% would need metaclasses and we don't want that. The method also now returns lists, instead of modifying attributes (risky)
2. Add type annotations. `UtmSplitter`s need a `type: ignore` because they redefine the interface of `get_bbox_list`.
3. Some more refactorings.
There are three similar functions for `_parse_split_parameters` that could be unified with some advanced `overload` use, I can try and do that if you feel it is necessary

Types in `areas.py`

---

sentinelhub/api/base.py
sentinelhub/download/sentinelhub_client.py
sentinelhub/download/session.py
tests/api/test_process.py
tests/conftest.py
tests/download/test_sentinelhub_client.py
tests/download/test_session.py

For issues: https://github.com/sentinel-hub/sentinelhub-py/issues/267, https://github.com/sentinel-hub/sentinelhub-py/issues/146
This PR adds the following:
- support from initializing `SentinelHubSession` object purely with an existing token,
- better support for caching session objects into `SentinelHubDownloadClient`.
Remaining things to do:
- As a proof of concept, implement session transfer in `eo-grow` `DownloadPipeline` which currently also has an issue that too many sessions get created when running with a Ray cluster.
- Write a documentation page about the session transfer procedure.
This will be done in the next PR.

Session transfer, part 1

---

examples/session_sharing.ipynb
sentinelhub/download/__init__.py
sentinelhub/download/session.py
tests/download/test_session.py

This PR adds 2 improvements:
- `SessionSharingThread` itself is now able to handle unclosed shared memory and warn users about it.
- `SessionSharing` object that is a more user-friendly interface around `SessionSharingThread`.

Improve handling of unclosed shared memory

---

requirements-dev.txt

Because Ray now works for Python 3.10.

Minor dev dependency update

---

requirements.txt
sentinelhub/download/sentinelhub_client.py
sentinelhub/download/sentinelhub_statistical_client.py
sentinelhub/download/session.py
tests/download/test_session.py

Package `requests-oauthlib` doesn't check for status errors of a response obtained from Sentinel Hub authentication service. Because of that it can raise a misleading `MissingTokenError`.
This PR solves the issue by adding a compliance hook into the process which checks for a response status and makes sure the correct error is raised. It also adds units tests for it.

Compliance hook for Sentinel Hub authentication

---

sentinelhub/areas.py

It seems that the service can also return a response with missing `bufferX` and `bufferY` parameters.

BatchSplitter fix - handled case where bufferX or bufferY would be missing

---

sentinelhub/config.py
tests/test_config.py

A useful functionality of `SHConfig` class that allows checking if 2 instances have the same parameters.

SHConfig.__eq__ method

---

examples/batch_processing.ipynb
pyproject.toml

This is a short-term improvement for https://github.com/sentinel-hub/sentinelhub-py/issues/296

Improved handling of imports from utils.py

---

requirements-dev.txt
sentinelhub/api/batch/statistical.py
sentinelhub/api/batch/utils.py
tests/api/batch/test_utils.py

Added tests for batch monitoring utility functions.
I also thought about including batch status next to any of the 2 progress bars. However, I don't see a nice place for it. Any option I try it looks weird, suggestions welcome. Otherwise, we can also drop this idea because it's not that important.
At the end it turned out `pytest-mock` works a bit differently in Python 3.7 so I had to skip tests for that Python version. :see_no_evil:

Tests for batch monitoring utils

---

sentinelhub/api/base.py
sentinelhub/api/batch/process.py
sentinelhub/api/batch/statistical.py
sentinelhub/api/byoc.py
tests/api/test_byoc.py

In the previous version both mypy and PyCharm were complaining about `other_data` parameter not being specified if someone tried to initialize an instance of a dataclass decorated with `@dataclass_json`.
This was solved by specifying the default value for this field and the only correct default values turned out to be `field(default_factory=dict)`.

Improved handling of CatchAll

---

docs/source/_templates/module.rst_t
docs/source/_templates/package.rst_t
docs/source/conf.py
requirements-docs.txt

The new documentation built for this branch is available [here](https://sentinelhub-py.readthedocs.io/en/docs-github-url/index.html). You can see that "Edit on GitHub" link on every single page now points to the correct source of the page.
Notes:
- This PR should be merged with squash because some commits contain unsuccessful attempts.
- After this is merged deactivate source build for `docs/github-url` branch.

Fixed GitHub URL links in documentation

---

.github/workflows/ci_action.yml

CI tests now trigger on pull requests, and push events only trigger them on the master and develop branch. Overall this should decrease the amount of redundant tests, but allow us to test PR branches.
Settings have already been modified in such a way that ALL workflows of outsider collaborators need to be run by a team member.
Tests run for PRs for forks don't include integration tests, so that we have no need for sharing secrets.

Improve triggers for running CI

---

sentinelhub/api/catalog.py
tests/api/test_catalog.py

The main changes are to the querying, since now we use the `filter` parameter in CQL2 instead.
The tests were also changed, because the old tests did a very poor job (if you just disabled querying/filtering they still all passed).

Adjust the catalog client to use the catalog 1.0.0

---

tests/api/test_byoc.py

in a recent update they now return additional information about BYOC tiles, the tests have been updated to reflect that.

Update BYOC tests now that ingestion information is returned

---

examples/byoc_request.ipynb

`datetime.datetime.fromisoformat()` can not parse all datetime strings compatible with ISO8601. It for example does not accept `Z` to specify UTZ. 
This was replaced with `dateutil.parser.parse()` which is also used in the package to parse dt strings.

BYOC Example: Replaced ISO parsing with dateutil

---

sentinelhub/api/batch/statistical.py
sentinelhub/api/statistical.py

The regular statistical API already did that. However it did that in a mutable way, which we now avoid by copying elements that are to be adjusted.

Add dataFilter defaults of {} to batch statistical

---

requirements-dev.txt
tests/test_config.py

Currently there is a small possibility of credentials being revealed in the tests if a test fails.
With this I introduce a fixture that caches the current config.json, and restores it after the tests. The first test (on which all other depend) checks that the config no longer contains credentials. If it still does, the test suite is aborted.

Refactor config tests, try to improve security

---

sentinelhub/api/batch/process.py
sentinelhub/areas.py
sentinelhub/geometry.py
tests/aws/test_data.py
tests/aws/test_data_safe.py
tests/aws/test_request.py
tests/test_geometry.py

This will slim down the code required and improve safety due to better typing.
It additionally forces the users to properly look at their data before initializing the class. 
I also silenced AWS warnings so that it is easier to detect warnings when running the test suite.

Restrict valid `BBox` inputs

---

sentinelhub/api/ogc.py
sentinelhub/api/opensearch.py
sentinelhub/api/wfs.py
sentinelhub/geometry.py
sentinelhub/geopedia/core.py
tests/test_geometry.py

It is clear that `"0,0,10,5"` is in no way an accurate representation of `BBox((0, 0), (10, 5), CRS(1234))` since it has no notion of the CRS.
The code makes it clear it was used as a crutch to 'jsonify' the bbox, but that is not the way to go. The old methods were adjusted to jsonify the BBox directly. 
A warning was added that the output will be changed in the future.

Deprecate `BBox.__str__`

---

sentinelhub/api/ogc.py
sentinelhub/api/wfs.py
sentinelhub/config.py
sentinelhub/download/session.py

It makes no sense to have only a select few URLs on the config. So either we add the methods for all other URLS or we scrap the one-liners and inline them (like it's already done in Catalog API).

Deprecate and avoid methods for certain urls

---

sentinelhub/__init__.py
sentinelhub/api/fis.py
sentinelhub/api/ogc.py
sentinelhub/constants.py

Since both OGC and FIS are not actively maintained it makes no sense to keep the API-specific files in the `constants.py` module.
This shouldn't break much code because they are imported in the top `__init__`. Also the services are deprecated, so we dont need to be that careful there.

Move OGC and FIS enums to the api files

---

sentinelhub/api/batch/process.py
sentinelhub/areas.py

This is one of those "Its so easy, and yet so hard." problems.
The idea is really simple, if there is no `geometry`, just take the geometry of the `bbox`. But since both getters are throwing errors upon non-definition, we only have a private method that lets us check. But that again does not seem right, since it's a private method...
I am open to suggestions.
Closes #337

Fix splitter issue when batch geometry is missing

---

setup.py

Talked with the team, tested it out. It doesn't seem to work, probably hasn't worked for a while.
After disabling the `try except` blocks it seems like importing any non std package during the setup results in a failure. Importing from the package you're installing seems to work, but since `sentinelhub` relies on `numpy` it dies on importing since it tries to import `numpy` along the way.
Let's scrap this and start from scratch.

Remove old mechanism for config persistence

---

sentinelhub/api/batch/statistical.py
sentinelhub/api/statistical.py

Before SH 4.172.0 the `dataFilter` field was mandatory, but now it is no longer. We can thus simplify both statistical APIs

remove workaround for requests with no  dataFilter

---

Makefile
pyproject.toml
requirements.txt
sentinelhub/commands.py
sentinelhub/config.py
setup.py
tests/test_config.py

Changes:
- No more global cache!
- Config is moved to a standardized user appdata location (`~/.config/sentinelhub/config.json` for Linux users)
- Credentials are masked by default, applies only to `str` and `repr` (not sure why that was not the case...)
- lots of refactoring
a separate MR shall introduce user profiles to remedy the loss of 'managing-different-credentials-through-python-envs'

Experimental new config setup

---

sentinelhub/commands.py
sentinelhub/config.py
tests/test_config.py

- removes dictionary-style access
- renames `get_config_dictionary` to the shorter and more common `to_dict` (am willing to accept new names as well). `hide_credentials` is now a parameter, the on at `__init__` only controls masking in `repr` and `str`
- class attributes specifying which attributes are regular fields and which are credentials have been changed to tuples. The `get_params` accessor is used instead of direct access, allowing us to remove duplication.

Further changes to SHConfig

---

tests/test_config.py

1. Did some refactoring (mostly renaming)
2. Removed old `ray` test because it was added due to issues with the global cache, which we have since removed
I mostly glanced it over, so any further suggestions are welcome.

Refactor config tests

---

sentinelhub/config.py
tests/test_config.py

- environment has precedence over everything
- for now only PROFILE, CLIENT_ID and CLIENT_SECRET can be set in environment. If there will be a need for more, we can add them later
- whenever a setting is overridden by the environment, I added a debug log. I am not sure if this is necessary (it would shorten the code if not).

Let `SHConfig` use environment

---

Makefile

We didn't allow wheel releases because of the `config.json` file in the repo (and the fear of non-persistence, which didn't even work anyway).
Now nothing is holding us back.

Enable releasing as a wheel

---

sentinelhub/commands.py
sentinelhub/config.py
tests/test_config.py

Before it was used for two things:
1. The config had to be reset before release in order to avoid leaking credentials
2. The user maybe wanted a fresh set of configuration? Or reset some to defaults?
Now these issues are solved:
1. The file is not part of the repo, its incredibly unlikely to release it.
2. With user profiles the user can just create a new profile. And since settings in the profile only override, you can just remove lines for parameters that you no longer wish to be non-default.

Remove the reset functionality of SHConfig

---

sentinelhub/_version.py

we usually do this just before release, but it will enable the use of develop with eo-grow (after https://github.com/sentinel-hub/eo-grow/pull/206)

increase version to 3.9.0

---

README.md
docs/source/configure.rst
docs/source/custom_reference/sentinelhub.rst
docs/source/install.rst
examples/byoc_request.ipynb
sentinelhub/aws/client.py
sentinelhub/commands.py
sentinelhub/config.py

Mainly changed `config.json` to `config.toml`.
Adjusted the page talking specifically about how to set up the configuration (it's built [here](https://sentinelhub-py.readthedocs.io/en/fix-docs/configure.html))

Adjust docs to account for SHConfig changes

---

sentinelhub/api/catalog.py
tests/api/test_catalog.py

Changes:
- port the utility function and update it a bit
- add tests
Added to Catalog API because it basically relies upon it, so I see it as an extra utility built on top of the class.

Move get_timestamps utility to sh-py

---

sentinelhub/api/catalog.py
sentinelhub/evalscript.py

Nothing major, just minor changes due to some faulty revert in the past:
- fix `get_available_timestamps` function parameter default
- fix indentation in evalscript template

Minor indentation and parameter default fixes

---

pyproject.toml

It has been removed from the PyPI. Our builds are failing but it looks like it's not needed anywhere.

Remove codecov dependency

---

sentinelhub/geometry.py

Had to inspect the shapely code to get the errors a bit more understandable (attribute errors are hard to decipher in such cases).
Tested that it works with `gpkg` now (as you suggested).

Generalize Geometry class to better leverage shapely for parsing values

---

.github/workflows/ci_action.yml
pyproject.toml
sentinelhub/data_collections.py

Extending enums is problematic in 3.11, probably because the official implementation of Enums got upgraded in some ways.
If we use the class from `aenum` then it seems to work. Tests in eo-grow and eo-learn pass with this as well.

Official Python 3.11 support

---

.github/workflows/ci_action.yml

Improves the CI in the following ways:
- updated versions of actions
- use pre-commit action instead of doing it manually (seems to be faster, probably caching)
- add caching to python-setup action, this makes installation about 30% faster since most packages do not need to be downloaded (allegedly you can cache the whole python environment and gain some more speedup, but it requires another action)
- removed installation of non-python stuff, doesn't seem to affect our tests but makes installation 30% faster
- add `concurrency` option, which makes sure that whenever a PR is updated (a new commit) it cancels all outdated CI workflows, saving resources in cases where a 'quick fix' commit is added (for instance if the pre-commit complains)
Shaves off about 1min for all jobs on average :D

Add pip cache to CI actions

---

.github/workflows/ci_action.yml

This creates a nearly empty python cache which messes with other workflows that need python 3.8

DIsable cache in pre-commit workflow step

---

sentinelhub/api/base.py

In some cases the response does not contain a `"links"` section (started occurring for tilling grids. It now stops iteration if that happens.

Generalize sentinelhub feature iterator to avoid issues

---

sentinelhub/data_collections_bands.py

This adds the `QUALITY_FLAGS` S3_OLCI band to `MetaBands`
See docs for band description: https://docs.sentinel-hub.com/api/latest/data/sentinel-3-olci-l1b/#units

Added QUALITY_FLAGS band to S3_OLCI

---

sentinelhub/commands.py
sentinelhub/config.py
tests/test_config.py

~the saving is also unnecessary because the load method creates the file if needed~
saving is needed because we have one do-all command. Gotta figure this out

Make sh-config CLI use environmental variable

---

sentinelhub/config.py
tests/test_config.py

As noticed by you, if the file doesn't exist one could do the first initialization with `SHConfig("something")` and break the whole damn thing.
I added a test that now the first init fails for any non-default profile (since no such profile exists).

Config no longer falsely loads profiles if file doesn't exist

---

sentinelhub/api/byoc.py
sentinelhub/api/utils.py
sentinelhub/geometry.py

The issue happens when someone calls the `to_dict` method on the collection.
Sadly this is used in our code a lot :upside_down_face: would you consider this worthy of a release?

Fix bug that occurs with dataclass_json 0.62

---

.pre-commit-config.yaml
CHANGELOG.MD
sentinelhub/_version.py
sentinelhub/api/batch/statistical.py
sentinelhub/aws/client.py
sentinelhub/aws/data.py
sentinelhub/aws/request.py
sentinelhub/config.py
sentinelhub/exceptions.py
sentinelhub/geo_utils.py
tests/test_config.py

The deprecator from typing_extensions has additional benefits of IDEs picking it up
I wanted to deprecate our own deprecators, but then users would get spammed with stuff that they have no control over (since it would happen on import. So I want to wait with that (or just remove them after a while)

Deprecate the deprecator

---

CHANGELOG.MD
sentinelhub/_version.py
sentinelhub/api/base.py
sentinelhub/download/rate_limit.py
sentinelhub/download/sentinelhub_client.py
tests/download/test_rate_limit.py

I added a parameterized default retry time, which we can then set in all services.
I also already set a class parameter in the `SentinelHubService` base class which the subclasses just override.

Default retry time

---

CHANGELOG.MD
sentinelhub/_version.py
sentinelhub/download/sentinelhub_client.py
tests/api/test_process.py
tests/download/test_session.py

I was thinking of making this a major release since older versions might no longer cache sessions correctly.

Update session caching according to core auth changes

---

sentinelhub/config.py
tests/download/test_session.py

The old URL has a redirect, but we should switch to the correct one

Change auth endpoint default

---

sentinelhub/config.py
sentinelhub/download/sentinelhub_client.py
tests/download/test_sentinelhub_client.py

At the moment the default behaviour is to retry requests indefinitely when rate limits are reached on the server side. For some use-cases it would be helpful to limit this behaviour, and allow the calling code to handle this with some backoff mechanism. In particular, if multiple processes are submitting requests it does not make sense for them to compete over the finite rate limit.
To achieve this I have added a new config called `max_rate_limit_retries`, which is `None` by default. If this configuration has a numeric value we will raise an `OutOfRequestsException` once the number of download attempts has exceeded the configuration value. I am open to changing the naming if necessary.

Add configuration to limit rate limit retries

---

sentinelhub/api/batch/utils.py
tests/api/batch/test_utils.py

A simple addition with more descriptions.
Another option would be to run the `while` loop as long as the status is `PROCESSING`, but perhaps the user would be confused why the job doesn't move forward as soon as the progress bars hit 100%. An additional reason is that the suggested implementation is perhaps more informative

Wait for batch process API job to update status from PROCESSING to something else

---

sentinelhub/api/batch/utils.py
tests/api/batch/test_utils.py

- stops early if a job is canceled
- other small behavior and test updates

Stop batch job monitoring if a batch job is canceled

---

sentinelhub/areas.py
tests/test_areas.py

Sometimes the intersection will result in a geometry type LineString (or similar), for which the `is_empty` will return False, but `sentinelhub.Geometry` init will fail as the geometry is neither `Polygon` nor `MultiPolygon`.

Fix for is_empty vs non-empty area.
